{% set version = "0.1.1" %}
package:
    name: seamless-cli
    version: {{ version }}

build:
  number: 1

requirements:
  build:
    - python
  run:
    - openssl
about:
  summary: This is a collection of shell scripts wrapping the Seamless Docker image
