{% set version = "0.1.1" %}
package:
    name: seamless-cli-devel
    version: {{ version }}

build:
  number: 1

about:
  summary: This is a collection of shell scripts wrapping the seamless-devel Docker image
